### ISSUE TITLE
How to verify rsa-sha256 using publicKey

### ISSUE THREAD

**Issue by jmart1** [tomitribe/http-signatures-java#12]
I am trying to implement authentication using "rsa-sha256".  From what I understand a client will generate an RSA signature.  The server receiving the request will authenticate the request using the public key.  I been able to generate the signature using the PrivateKey and Signer classes.  But how do I conduct the verification using the PublicKey?

When I tried replacing the PrivateKey with the PublicKey it fails on line 61 in Signer class....

            this.sign = new Asymmetric(PrivateKey.class.cast(key));

Any idea how the signature verification can be done using the PublicKey?

**Comment by jmart1** [comment]
I found a pull request in this project for a class called Verifier that does exactly what I need.  I tested it out and it works.  Thank you to @mpuzar for creating Verifier.

**Comment by jeanouii** [comment]
Indeed, we need a Verifier kinda class. The PR looks good. Lemme see if I can merge it
