### ISSUE TITLE
The Signature header

### ISSUE THREAD

**Issue by mpuzar** [tomitribe/http-signatures-java#13]
I've had a discussion with some colleagues and it seems that the client and server are supposed to send different headers - `Authorization` for the client, `Signature` for the server, where their content is the same(?) except for the fact that the `Authorization` header has a prefix. Examples from the draft:

> Authorization: Signature keyId="Test",algorithm="rsa-sha256",
> headers="(request-target) host date content-type digest content-length",
> signature="jgSqY(...)78w="

> Signature: keyId="Test",algorithm="rsa-sha256",
> headers="(request-target) host date content-type digest content-length",
> signature="jgSqY(...)78w="

`Signature.toString()` assumes we want to send the `Authorization` header and, hence, always appends the "Signature " prefix, which makes it impossible to use directly for the `Signature` header.

The simplest way to add functionality to create the `Signature` header as well, is to change the scope of `Signature.normalize()` from private to public, and use that one on the computed signature string. It is not the cleanest way, but it would be backwards compatible. Another way is to rewrite and split the `toString()` method and make a clear distinction between the two uses.

What do you suggest?

**Comment by liamdennehy** [comment]
> `Authorization` for the client, `Signature` for the server

No.

- ``Authorization`` is probably exclusively a client header and used for [HTTP Authentication](https://tools.ietf.org/html/rfc7235). This is typically seen in OAuth2 flows, or directly on a target endpoint to authenticate the client (ie prove they have permission to perform the action).
- ``Signature`` can be generated by either the client or server. It is intended to be used primarily to ensure the integrity of the content - that it was generated by the client _or_ server and has not been altered beyond the signer's original intention. It can also be used to authorise the client, but it is not uncommon to see both headers in this case that serve their respective purposes.

This is explained in the [Introduction to draft version 11](https://tools.ietf.org/html/draft-cavage-http-signatures-11#section-1) of the protocol. If it is not clearly explained there, do [raise an issue](https://github.com/w3c-dvcg/http-signatures/issues) with your comments/suggestions to improve.

**Comment by jeanouii** [comment]
Not an issue as explained above.
