### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by peacekeeper** [tomitribe/http-signatures-java#14]
Perhaps you would like to add a license such as MIT or Apache-2 to your project?

**Comment by danielsoro** [comment]
Hi @peacekeeper,
The project is under Apache License 2.0

**Comment by peacekeeper** [comment]
Oh okay, yes now I see it in the source code. I was looking for a LICENSE file at the root level like most repos have it. Thank you.

**Comment by danielsoro** [comment]
No problem.
Thanks for your question. :)
