### ISSUE TITLE
Support for additional algorithms - ECC DSA

### ISSUE THREAD

**Issue by evenaglia** [tomitribe/http-signatures-java#15]
My employer is considering this library for verifying signed HTTP requests, but we use Elliptic Curve DSA key pairs to identify the caller.

Any chance we can add support for the following algorithms?
* ECDSA_SHA1
* ECDSA_SHA256
* ECDSA_SHA384
* ECDSA_SHA512

I would be happy to submit a patch or pull-request with the requested changes when they are ready.

**Comment by jeanouii** [comment]
All merged!
Thank you.
