### ISSUE TITLE
Signature parsing

### ISSUE THREAD

**Issue by ghost** [tomitribe/http-signatures-java#18]
The https://tools.ietf.org/html/draft-cavage-http-signatures-10#page-4 specifies that keyId can, for exmple, contain LDAP DN's. The implementation of Signature.fromString(String) fails if the value of keyId parameter contains commas.

**Comment by dblevins** [comment]
Your PR has been merged and released.  Thank you so much.

Looks like you opened a github account just for this contribution.  We're honored!  How did you learn of HTTP Signatures?

**Comment by silviuburceadev** [comment]
@dblevins this ticket should be closed.
