### ISSUE TITLE
Time constant MAC comparison

### ISSUE THREAD

**Issue by bgrenacher** [tomitribe/http-signatures-java#21]
The MAC in https://github.com/tomitribe/http-signatures-java/blob/tomitribe-http-signatures-1.1/src/main/java/org/tomitribe/auth/signatures/Verifier.java is compared with a non time-constant algorithm (Arrays.equals).
I suggest to use MessageDigest.isEqual to prevent possible timing attacks.

**Comment by jgallimore** [comment]
Thanks for reporting this. I've created a PR to fix this, which if it looks ok, I'll merge in and get a new release made. https://github.com/tomitribe/http-signatures-java/pull/22

Can you see any further issues?

**Comment by bgrenacher** [comment]
Not any other than the already reported issues.

**Comment by dblevins** [comment]
Merged and released.  Thank you so much for the suggestion!
