### ISSUE TITLE
lowercase key during the lookup required keys from the headers map 

### ISSUE THREAD

**Issue by paissad** [tomitribe/http-signatures-java#27]
https://github.com/tomitribe/http-signatures-java/blob/6623951b065c098c0c3415841a399a5c95675ff4/src/main/java/org/tomitribe/auth/signatures/Signatures.java#L38

Isn't it worth to do "key.toLowercase()" while retrieve the value from the map ?
Or maybe it was done that way in purpose and for the good / best reasons ?

Regards

**Comment by jeanouii** [comment]
Yes the required headers are already lower cased per spec reasons.
