### ISSUE TITLE
Add support for RSASSA-PSS Signature algorithm

### ISSUE THREAD

**Issue by luddwichr** [tomitribe/http-signatures-java#29]
Currently, the library does not support any of the algorithms added by [JDK-8146293](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8146293), i.e.:
- SHA512/224withRSA (1.2.840.113549.1.1.14)
- SHA512/256withRSA (1.2.840.113549.1.1.15)
- RSA-PSS (1.2.840.113549.1.1.10)
- SHA1withRSAandMGF1
- SHA224withRSAandMGF1
- SHA256withRSAandMGF1
- SHA384withRSAandMGF1
- SHA512withRSAandMGF1
- SHA512/224withRSAandMGF1
- SHA512/256withRSAandMGF1

(see also [JDK-82334183](https://bugs.openjdk.java.net/browse/JDK-82334183)])

The changes probably only need to be applied to the enum [Algorithm](https://github.com/tomitribe/http-signatures-java/blob/master/src/main/java/org/tomitribe/auth/signatures/Algorithm.java).
Ii am not sure which naming pattern to apply to the enum names as well as portable name and jmvName attributes. Any suggestions?

**Comment by AndreeaFluerasu** [comment]
I would also need this feature. Could you please tell me if you intend to implement it? Thank you!

**Comment by sebastien-rosset** [comment]
I've raised PR #32  for RSASSA-PSS

**Comment by sebastien-rosset** [comment]
Can you check #32 and #38? Does it cover your needs?

**Comment by luddwichr** [comment]
@sebastien-rosset looks perfect to me! thanks so much for your effort!
