### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by crave-pacheco** [tomitribe/http-signatures-java#34]
Hello, I want to use this library but I don't see the license information. I saw that maven's page for this library mentions it has "The Apache Software License, Version 2.0" but I'm not sure.
Would it be possible to add it or clear this please?

**Comment by cesarhernandezgt** [comment]
Hi @crave-pacheco 
That's a good question. Yes, as far as I know, the license is Apache version 2.0.
I just created a PR to include the license file in the project root: 
https://github.com/tomitribe/http-signatures-java/pull/35

**Comment by crave-pacheco** [comment]
Thank you!
