### ISSUE TITLE
Suggestions for 1.5 release

### ISSUE THREAD

**Issue by sebastien-rosset** [tomitribe/http-signatures-java#42]
In the reference section, I suggest you add a link to the latest draft specification instead of draft v4. The URL is https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00

PR: #43

Do you have a tentative date for the 1.5 release?

**Comment by jeanouii** [comment]
Hey Sebastien. 

Thanks for the patches.
I'll be closing this issue.

I don't have any particular preference for a 1.5 release. I'll check it out and see if I can produce a release for you.

**Comment by tomitribe-dev** [comment]
1.5 release should already be done @jlmonteiro.
