### ISSUE TITLE
signature header is separate from Authorization

### ISSUE THREAD

**Issue by nhomble** [tomitribe/http-signatures-java#45]
In ```Signature```, creating a signature from string comes from ```public static Signature fromString(..)``` but this seems deprecated. In an older version of the rfc, https://www.ietf.org/archive/id/draft-cavage-http-signatures-12.txt, this was correct. In the current draft rfc, https://www.ietf.org/id/draft-ietf-httpbis-message-signatures-00.html#name-the-signature-http-header, section 4 specified a new header ```Signature:``` and doesn't reuse the auth scheme defined in https://tools.ietf.org/html/rfc2617.

Since the rfc is evolving, maybe we could keep this method (deprecated) with a method name specific to ```Authorization``` and then create a new method to parse signature header. I am sure existing clients will appreciate the backwards compatibility.

**Comment by jeanouii** [comment]
I haven't got time to get into the spec, so fully relying on what you said.
I am fully in favour of maintaining backward compatibility if we can.

Would you like to create a PR for it?

**Comment by nhomble** [comment]
Totally @jeanouii I'll come up with something and link back to the spec so you can ensure this library continues to match. Thanks!

**Comment by dblevins** [comment]
This should now be fixed and available in release 1.7.  If there is still an issue, please reopen.
