### ISSUE TITLE
[documentation] example signer has syntax issue

### ISSUE THREAD

**Issue by nhomble** [tomitribe/http-signatures-java#46]
```java
final Signature signature = new Signature("key-alias", "hmac-sha256", null, "(request-target)"); // (1)
```

this example from the README no longer works. Assuming the ```null``` was for the algo specs, the example is missing the ```Algorithm``` and the headers should be a list.

**Comment by dblevins** [comment]
This should now be fixed and available in release 1.7.  If there is still an issue, please reopen.
