### ISSUE TITLE
There is no Verifier class

### ISSUE THREAD

**Issue by DinoChiesa** [tomitribe/http-signatures-java#7]
This library is useful only for creating HttpSignatures.  It cannot be used unmodified for verifying received signatures.  What is necessary is a class that is a companion to Signer, possibly called Verifier, which verifies received signatures.

**Comment by jeanouii** [comment]
Hi,

That could be interesting yes.
With some small refactoring we could reuse some internal parts.

Jean-Louis

**Comment by mpuzar** [comment]
I have implemented the Verifier class and sent a pull request (#11). I hope the implementation is acceptable and that it can be added to 1.1 and released soon.

**Comment by tomitribe-dev** [comment]
Thanks for the PR. I'll review and give it a try tonight.

Jean-Louis

--
Jean-Louis Monteiro
http://twitter.com/jlouismonteiro
http://www.tomitribe.com

**Comment by jeanouii** [comment]
Hi @mpuzar ,

Just saw there is still some discussions around your PR. Are you still working on it?

JLouis

**Comment by mpuzar** [comment]
It was only a comment that needed to be corrected, which I've done now. Feel free to merge it, and if you later want to add more detailed comments you may do so.

**Comment by jeanouii** [comment]
Merged. Thanks for the contribution.

**Comment by mpuzar** [comment]
My pleasure. Any idea on when 1.1 might be released to the public?

**Comment by tomitribe-dev** [comment]
There is no plan for it, but I can probably make it happen beginning of
next week?
Would that work for you?

--
Jean-Louis Monteiro
http://twitter.com/jlouismonteiro
http://www.tomitribe.com

**Comment by mpuzar** [comment]
Sounds wonderful, thanks.

**Comment by BassExtractor** [comment]
I am interested in using this library, but for me it seems like the 1.1 release is nowhere to be found. It is not accessible from Nexus central either. In the releases tab I only see version 1.0, has the 1.1 release become public or is it secret?
